# fly.toml app configuration file generated for clams-tech-server on 2025-01-13T20:18:47+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'clams-tech-server'
primary_region = 'iad'

[build]

[env]
DATA_DIR = '/data'
DOMAIN = 'clams.tech'
PHOENIXD_HOST = 'phoenixd.internal'
PORT = '8080'

[[mounts]]
source = 'clams_tech'
destination = '/data'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'
